# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}
  name: climate-insights # kpt-set: ${cluster-name}
  namespace: KCC-NAMESPACE
  annotations:
    cnrm.cloud.google.com/project-id: GCP-PROJECT-ID # kpt-set: ${project-id}
    cnrm.cloud.google.com/blueprint: kpt-pkg-fn-live
  labels:
    created-by-arete: "true"
spec:
  description: GKE Autopilot cluster running Climate Insights Workloads
  enableAutopilot: true
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterSecondaryRangeName: gke-pods-range # kpt-set: ${gke-pods-range-name}
    servicesSecondaryRangeName: gke-services-range # kpt-set: ${gke-services-range-name}
  location: GCP-REGION # kpt-set: ${region}
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: "01:00"
  masterAuthorizedNetworksConfig:
    cidrBlocks: # kpt-set: ${auth-network}
      - cidrBlock: 10.0.0.0/28
        displayName: private-net
  networkRef:
    external: default # kpt-set: ${network-name}
  subnetworkRef:
    external: ce-subnet # kpt-set: ${subnetwork-name}  
  networkingMode: VPC_NATIVE
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: climate-insights-pubsub # kpt-set: ${cluster-name}-pubsub
    enableNetworkEgressMetering: true
    enableResourceConsumptionMetering: true
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.0.0/28
  workloadIdentityConfig:
    # Workload Identity supports only a single namespace based on your project name.
    # Replace ${PROJECT_ID?} below with your project ID.
    identityNamespace: GCP-PROJECT-ID.svc.id.goog # kpt-set: ${project-id}.svc.id.goog
  nodeConfig:
    serviceAccountRef:
      name: CI-SERVICE-ACCOUNT # kpt-set: ${service-account}
      namespace: KCC-NAMESPACE # kpt-set: ${namespace}
